id: P009559
initial_creation_type: ocr
source_metadata:
  id: bdr:W14132
  title: མུན་འཇོམས་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    e08dc73a3a144d7b9227524b809f4ab2:
      image_group_id: I4730
      title: ''
      volume_number: 1
      total_pages: 444
      base_file: v001.txt
