id: IA14D34AD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T02:50:08+00:00'
last_modified: '2022-06-08T11:53:23.370529+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W14132
  title: མུན་འཇོམས་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    59D5:
      image_group_id: I4730
      title: ''
      total_pages: 444
      order: 1
      base_file: 59D5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
